### ISSUE TITLE
Docket Scraping #2: Parsing the Docket & Court Summary PDFs & outputting CSVs

### ISSUE THREAD

**Issue by bander567** [CodeForPhilly/pbf-scraping#13]
**Requirements**
— generates daily
— taking only what is needed per the Data Dictionary (https://drive.google.com/drive/folders/1cJvp_5bhiN6Sgwj5pcwsxXg1iPmDr-TK)
— using GitHub actions to run 

**Discussion Notes**
— To combine with current New Criminal Filing CSVs by recently made scraping script (likely not our permanent solution)
— preferably using Python 
— will later be anonymized for analysis

**Comment by adamrlinder** [comment]
Closing this, as we now have a script in place and I will create individual issues for each improvement to be made to that script.
