### ISSUE TITLE
Docket Scraping #3: Combining all 3 data source CSVs to one large CSV

### ISSUE THREAD

**Issue by bander567** [CodeForPhilly/pbf-scraping#14]
**Requirements:** 
- Joining data sources into one large csv for analysis, using Docket ID as primary key
- Sending to an S3 bucket preferably using GH actions

_Note_: Will update as required pre-work is completed

**Comment by adamrlinder** [comment]
Closing this issue as we are now no longer planning to combine all three data sources into one csv.
