### ISSUE TITLE
Set up a github action to email a csv daily

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/pbf-scraping#2]
Todo:

* sends an email every day
* attaches a CSV
* can send email to multiple addresses

Note that once #3 is completed, we'll have the body of the email, and a properly formatted CSV to send!

https://github.com/marketplace/actions/send-email

**Comment by tuh16620** [comment]
The dawidd6 action (linked above) works in sending multiple email addresses and attachments. The changes to be made to get it to work in our workflow is:

- make secrets.MAIL_USERNAME an email that has "Allow less secure apps" on (https://support.google.com/accounts/answer/6010255?hl=en)
- change the "attachments" value to "output/*"

**Comment by RaymondFallon** [comment]
Is there a reason this issue is marked as "Done" but is not yet closed?
