### ISSUE TITLE
Move scraping and pdf parsing scripts into analyses folder

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/pbf-scraping#26]
It looks like there are a few different pieces of activity going on in this repo now...

1. scraping from new criminal filings
2. reporting based on scraped data on athena
3. parsing docket PDFs

@chriscardillo and I created an analyses folder, to hopefully make it easier for people to keep track of this work, or start new things.

1. move scripts from main directory to a folder in analyses (e.g. `docket_pdf_parsing` or something)
2. for anything that generates an output, we can create a job using github actions to push it to https://codeforphilly.github.io/pbf-scraping/)

![image](https://user-images.githubusercontent.com/2574498/93221941-55ee4b00-f73c-11ea-9c85-8fc04e2c372f.png)

**Comment by RaymondFallon** [comment]
Fixed in #30 

☝️ Does GitHub handle magic comments like this?

**Comment by machow** [comment]
Ah yeah--thanks! Noticed it linked in the PR :)
