### ISSUE TITLE
Fix broken "Main" and "Report website" actions

### ISSUE THREAD

**Issue by adamrlinder** [CodeForPhilly/pbf-scraping#41]
As of earlier this week, both the "Main" and the "Report website" actions started failing on the step where they install the dependency kiwisolver. I've copied the error below. It seems to be mad that wheel isn't installed. I had tried in another branch to add `pip install wheel` as a step, but that ended up causing some other errors. 

```Collecting kiwisolver==1.2.0
  Downloading kiwisolver-1.2.0.tar.gz (52 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bt1i_gbq/kiwisolver/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bt1i_gbq/kiwisolver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-znng_rw6
         cwd: /tmp/pip-install-bt1i_gbq/kiwisolver/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-wvdb3mxv/cppy/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-wvdb3mxv/cppy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-99elgp8h
           cwd: /tmp/pip-wheel-wvdb3mxv/cppy/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.9.0/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp68gj73mg', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.```

**Comment by jshin313** [comment]
Hi. I added `sudo apt-get install libxml2-dev libxslt-dev python-dev -y` to analysis.yml in addition to the `pip install wheel` and that seems to make the the actions move past the installation of kiwisolver and lxml. However, it seems like a new error appears when the actions can't install pandas properly:

```
Successfully built future glob3 jupytext kiwisolver lxml MarkupSafe matplotlib numpy pandocfilters pdfquery Pillow PyPDF2 pyrsistent PyYAML scipy SQLAlchemy statsmodels tornado
ERROR: Could not build wheels for pandas which use PEP 517 and cannot be installed directly
Failed to build pandas
Error: Process completed with exit code 1.
```

https://github.com/jshin313/pbf-scraping/runs/1265197900?check_suite_focus=true

But the action takes around an hour to complete as well.

I looked at the issues for the actions/python repo and found that someone else is having a similar problem: https://github.com/actions/setup-python/issues/133
Unfortunately, the issue is open with no responses.

**Comment by RaymondFallon** [comment]
I just posted in Slack, but I opened a new branch: `bugfix/main-in-container`, that converts our Main action to execute in a container, the way we got `download.py` to run. [Here is the successful action](https://github.com/CodeForPhilly/pbf-scraping/runs/1268783041?check_suite_focus=true), but I don't have access to the email or AWS to see if the success was real or not.

**Comment by RaymondFallon** [comment]
For the record, I should add: I am _not_ a Docker expert. If we are dubious of converting more of our workflow to this mysterious and overhyped technology, I will not object at all.

**Comment by jshin313** [comment]
I think I got the Report Website somewhat working in a container in this branch:
https://github.com/CodeForPhilly/pbf-scraping/tree/bugfix/report-in-container
It's probably not the most efficient way to do it, so it could probably be improved.
Successful Action:
https://github.com/CodeForPhilly/pbf-scraping/actions/runs/338625025
