### ISSUE TITLE
scrape statute codes from dockets

### ISSUE THREAD

**Issue by irishryoon** [CodeForPhilly/pbf-scraping#49]
Scrape statute code for each charge. They can be found in the "charges" section of the docket under column "statute". In the attached example, these correspond to "18 S6106 SSA1", ...  

This will help encode the different types of charges for analysis purposes.  

![docket_statute](https://user-images.githubusercontent.com/16123954/97497452-e1b0e500-1940-11eb-98b7-a1824d766a9c.png)

**Comment by bertamb** [comment]
Done
