### ISSUE TITLE
Add "charge category" lookup to docket parsing

### ISSUE THREAD

**Issue by adamrlinder** [CodeForPhilly/pbf-scraping#56]
We discussed adding support for looking up what category a charge falls into.

**Comment by irishryoon** [comment]
I created a dictionary for converting statute info to offense type. The dictionary is based on all the offense types that I've seen in around 300 dockets.

If a very unique offense appears in a new docket, it will print a warning and encode the particular offense type as 'NA'

To update the offense type dictionary in the future, just edit the 'offense_type.py' script
